### ISSUE TITLE
Chọn đề tài dự án

### ISSUE THREAD

**Issue by LongNB8** [son14071999/group_07#1]

**Comment by LongNB8** [comment]
zô thảo luận đi

**Comment by tham18091999** [comment]
theo mk nghĩ thì chúng ta nên làm web

**Comment by tham18091999** [comment]
về Web thì có nhiều đề tài nhưng mk nghĩ nên làm mấy web quản lý 👍 
1. Quản lý cửa hàng : bán coffe, trà sữa,... với chủ đề này thì nên có nhiều tính năng mới như lưu lại thông tin khách hàng để có biện pháp tư vấn và chiết khấu phù hợp
2. Quản lý  phòng tập : Yoga, GYM, ....
3. Quản lý thư viện

**Comment by LongNB8** [comment]
sao không làm web bán hàng cho dễ

**Comment by tham18091999** [comment]
web bán hàng thì lại phổ biến quá ý

**Comment by son14071999** [comment]
t thấy ý kiến 1 của Thắm oki đấy

**Comment by BuiThiVui** [comment]
web về hỗ trợ thi trực tuyến thì sao

**Comment by son14071999** [comment]
hello cả nhà. chọn đề tài nào:)

**Comment by LongNB8** [comment]
t thấy làm bán hàng or quản lý cái gì đó là dễ nhất r

**Comment by son14071999** [comment]
t chọn đề tài đầu tiên nhóm đặt ra: Thi trực tuyến Vì:
+)t nghĩ đây là đề tài khá mới so vs các nhóm-->độc
+)Nhu cầu thị trường chưa bão hòa như các web bán hàng
+)Kho dl đề thi vô cùng phong phú
+)Nó ko phổ biến-->khó hơn 1 chút so với các đề tài phổ biến khác vì ít tài liệu tham khảo

**Comment by son14071999** [comment]
Làm đề tài ko ai chọn. Đi dường chưa ai đi nó ms thú vị:). Đó là ý kiến của t. còn mn?

**Comment by LongNB8** [comment]
thấy cũng ok vừa hỏi vài nhóm thấy nhiều đứa bảo làm bán hàng t

**Comment by BuiThiVui** [comment]
vậy cũng được thế bầu leader rồi triển khai nhé

**Comment by tham18091999** [comment]
T thấy ý kiến Sơn hay đấy


Vào Th 2, 21 thg 10, 2019 lúc 21:35 son14071999 <notifications@github.com>
đã viết:

**Comment by LongNB8** [comment]
thế chốt luôn nha web thitructuyen <-

**Comment by BuiThiVui** [comment]
vậy Sơn làm leader luôn nhé

**Comment by LongNB8** [comment]
cho sơn làm đi có nhiều kn

**Comment by tham18091999** [comment]
Theo mk thì b Sơn luôn vì bạn ấy là đầu não của ys tưởng này và trong quá
trình học tập
 thì Sơn cũng là người khá nhất


Vào Th 2, 21 thg 10, 2019 lúc 21:36 BuiThiVui <notifications@github.com> đã
viết:

**Comment by son14071999** [comment]
t nghĩ nên cho ng có nhiều kinh nghiệm làm web nhất làm leader đó là Long Soái Ca:)

**Comment by BuiThiVui** [comment]
mình cũng thấy Sơn khá nhất nhóm., có tinh thần trách nhiệm cao hehehhe nhận đi rồi mai đến bàn cụ thể thêm về đề tài nha

**Comment by tham18091999** [comment]
Vậy chốt b Sơn làm leader nhé

Vào Th 2, 21 thg 10, 2019 lúc 21:38 long <notifications@github.com> đã viết:

**Comment by LongNB8** [comment]
**Chốt kết quả ngày 21/10/2019**
- Sơn nhóm trưởng
- Đề tài : web dạng thi trực tuyến
Ai có ý kiếm gì ko để đóng issue.

**Comment by BuiThiVui** [comment]
okiiiiiii
